### ISSUE TITLE
Recent changes for v0.1.0.2 do not pass RubySpec

### ISSUE THREAD

**Issue by headius** [ruby/cgi#34]
The changes in v0.1.0.2 do not appear to pass RubySpec. Either the library needs to be fixed or the specs need to be updated.

See https://github.com/jruby/jruby/actions/runs/3535817028/jobs/5934245109 for an example job that failed on JRuby after updating to v0.1.0.2.

**Comment by headius** [comment]
Failing specs for convenience:

```
1)
CGI::Cookie#name returns self's name ERROR
ArgumentError: invalid name: "another cookie"
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:108:in `name='
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:91:in `initialize'
org/jruby/RubyClass.java:890:in `new'
/home/runner/work/jruby/jruby/spec/ruby/library/cgi/cookie/name_spec.rb:9:in `block in <main>'
org/jruby/RubyBasicObject.java:2677:in `instance_exec'
org/jruby/RubyArray.java:4686:in `all?'
org/jruby/RubyArray.java:1865:in `each'
/home/runner/work/jruby/jruby/spec/ruby/library/cgi/cookie/name_spec.rb:4:in `<main>'
org/jruby/RubyKernel.java:1052:in `load'
org/jruby/RubyBasicObject.java:2677:in `instance_exec'
org/jruby/RubyArray.java:1865:in `each'

2)
CGI::Cookie#name= sets self's expiration date ERROR
ArgumentError: invalid name: "another name"
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:108:in `name='
/home/runner/work/jruby/jruby/spec/ruby/library/cgi/cookie/name_spec.rb:17:in `block in <main>'
org/jruby/RubyBasicObject.java:2677:in `instance_exec'
org/jruby/RubyArray.java:[46](https://github.com/jruby/jruby/actions/runs/3535817028/jobs/5934245109#step:7:47)86:in `all?'
org/jruby/RubyArray.java:1865:in `each'
/home/runner/work/jruby/jruby/spec/ruby/library/cgi/cookie/name_spec.rb:14:in `<main>'
org/jruby/RubyKernel.java:1052:in `load'
org/jruby/RubyBasicObject.java:2677:in `instance_exec'
org/jruby/RubyArray.java:1865:in `each'

3)
CGI::Cookie.parse parses a raw cookie string into a hash of Cookies ERROR
ArgumentError: invalid name: "first cookie"
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:108:in `name='
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:79:in `initialize'
org/jruby/RubyClass.java:911:in `new'
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:195:in `block in parse'
org/jruby/RubyArray.java:1865:in `each'
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:187:in `parse'
/home/runner/work/jruby/jruby/spec/ruby/library/cgi/cookie/parse_spec.rb:10:in `block in <main>'
org/jruby/RubyBasicObject.java:2677:in `instance_exec'
org/jruby/RubyArray.java:4686:in `all?'
org/jruby/RubyArray.java:1865:in `each'
/home/runner/work/jruby/jruby/spec/ruby/library/cgi/cookie/parse_spec.rb:4:in `<main>'
org/jruby/RubyKernel.java:10[52](https://github.com/jruby/jruby/actions/runs/3535817028/jobs/5934245109#step:7:53):in `load'
org/jruby/RubyBasicObject.java:2677:in `instance_exec'
org/jruby/RubyArray.java:1865:in `each'

4)
CGI::Cookie.parse does not use , for cookie separators ERROR
ArgumentError: invalid name: "first cookie"
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:108:in `name='
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:79:in `initialize'
org/jruby/RubyClass.java:911:in `new'
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:195:in `block in parse'
org/jruby/RubyArray.java:1865:in `each'
/home/runner/work/jruby/jruby/lib/ruby/stdlib/cgi/cookie.rb:187:in `parse'
/home/runner/work/jruby/jruby/spec/ruby/library/cgi/cookie/parse_spec.rb:18:in `block in <main>'
org/jruby/RubyBasicObject.java:2677:in `instance_exec'
org/jruby/RubyArray.java:4686:in `all?'
org/jruby/RubyArray.java:1865:in `each'
/home/runner/work/jruby/jruby/spec/ruby/library/cgi/cookie/parse_spec.rb:4:in `<main>'
org/jruby/RubyKernel.java:1052:in `load'
org/jruby/RubyBasicObject.java:2677:in `instance_exec'
org/jruby/RubyArray.java:18[65](https://github.com/jruby/jruby/actions/runs/3535817028/jobs/5934245109#step:7:66):in `each'
```

**Comment by hsbt** [comment]
This is already fixed at https://github.com/ruby/ruby/commit/36f297e62108072b9377d927321928b994f66a93

**Comment by headius** [comment]
So that change will go into v0.1.0.3 and other maintenance releases? We need to get the security fix out for JRuby 9.3 ASAP, but the 2.7-only test and this regression have blocked us.

**Comment by hsbt** [comment]
There is no change in ruby/cgi repo. They are only in https://github.com/ruby/spec.

**Comment by headius** [comment]
Oh I see, then either @eregon or I will update JRuby's copy of the specs so we can move forward with the security release.

**Comment by headius** [comment]
Thank you for the help here!

**Comment by hsbt** [comment]
👍 Your welcome. We may move them to this repo from ruby/spec in the future.

**Comment by headius** [comment]
I would support moving library specs into the library repositories. 👍
